const SAVES_KEY='ironsworn-saves-v3';
const OLD_STORE_KEY='ironsworn-characters-v1';
const ACTIVE_KEY='ironsworn-active-character';
const DRAFT_KEY='ironsworn-working-draft-v3';
const WHITE_ID='shirogane';

const whiteTemplate={id:WHITE_ID,name:'白金',stats:{edge:3,heart:1,iron:2,shadow:1,wits:2},tracks:{health:5,spirit:5,supply:3,momentum:3,xp:1},vow:{title:'アデルを連絡拠点まで守る',progress:0},assets:[{assetId:'last-of-people',name:'最後の民',type:'カスタム',summary:'一族最後の生き残り。荒野で生きる力を持つ。',abilities:[['荒野の子',true,'荒野での行動を助ける。'],['獣を捌く者',false,'獣の扱いに長ける。'],['異邦の眼',false,'異文化を観察する。']]},{assetId:'herbalist',name:'薬草師',type:'パス',summary:'薬草を使った治療を得意とする。',abilities:[['薬草治療',true,'薬草を使った治療を強化する。'],['癒やし手',false,'他者を治療した時に恩恵を得る。'],['滋養食',false,'野営時の食事で回復を助ける。']]},{assetId:'raven',name:'肉',type:'相棒',summary:'鴉の相棒。策略・死の境・伝書に役立つ。',abilities:[['ずる賢い',false,'悪戯や盗みで行動を助ける。'],['知る者',false,'死に直面した時に助ける。'],['勤勉',true,'離れた相手への伝書や情報収集に使える。']]}],tattoos:{'道標':'ready','鷹目':'ready','守骨':'ready','影歩':'ready','狩牙':'ready','止血':'cool','熾火':'ready','息潜':'ready'},createdAt:'2026-08-19T00:00:00+09:00',updatedAt:new Date().toISOString()};
const clone=x=>JSON.parse(JSON.stringify(x));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function migrate(c){if(!c)return c;c.assets=Array.isArray(c.assets)?c.assets:[];c.tracks=c.tracks||{health:5,spirit:5,supply:5,momentum:2,xp:0};c.vow=c.vow||{title:'未設定',progress:0};c.tattoos=c.tattoos||{};return c}
function loadSaves(){let s={};try{s=JSON.parse(localStorage.getItem(SAVES_KEY)||'{}')||{}}catch(e){};if(!Object.keys(s).length){try{const old=JSON.parse(localStorage.getItem(OLD_STORE_KEY)||'{}')||{};Object.values(old).forEach(c=>{if(c&&c.id)s[c.id]=migrate(c)})}catch(e){}}if(!s[WHITE_ID])s[WHITE_ID]=clone(whiteTemplate);localStorage.setItem(SAVES_KEY,JSON.stringify(s));return s}
let saves=loadSaves();let activeId=localStorage.getItem(ACTIVE_KEY)||WHITE_ID;let draft=null;let detailIndex=null;
function saveSaves(){localStorage.setItem(SAVES_KEY,JSON.stringify(saves));localStorage.setItem(ACTIVE_KEY,activeId)}
function readDraft(){try{const p=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'null');return p&&p.id&&p.character?p:null}catch(e){return null}}
function writeDraft(){if(!draft)return;sessionStorage.setItem(DRAFT_KEY,JSON.stringify({id:activeId,character:draft}));localStorage.setItem(ACTIVE_KEY,activeId)}
function discardDraft(){draft=null;sessionStorage.removeItem(DRAFT_KEY)}
function startDraft(id,c){activeId=id;draft=migrate(clone(c));writeDraft();return draft}
function formalSave(){if(!draft)return false;draft.updatedAt=new Date().toISOString();saves[activeId]=clone(draft);saveSaves();writeDraft();return true}
function show(id){['homeScreen','newScreen','gameScreen'].forEach(x=>document.getElementById(x).classList.add('hidden'));document.getElementById(id).classList.remove('hidden')}
function abilityParts(x){if(Array.isArray(x))return{label:x[0]||'能力',active:!!x[1],description:x[2]||''};return{label:x?.label||'能力',active:!!x?.active,description:x?.description||''}}
function renderMomentum(){const h=document.getElementById('mtrack');h.innerHTML='';for(let v=-6;v<=10;v++){const b=document.createElement('button');b.textContent=v;b.onclick=()=>{draft.tracks.momentum=v;writeDraft();renderGame()};h.appendChild(b)}}
function renderVow(){const h=document.getElementById('vtrack');h.innerHTML='';for(let i=1;i<=10;i++){const b=document.createElement('button');b.textContent=i;b.onclick=()=>{draft.vow.progress=draft.vow.progress===i?i-1:i;writeDraft();renderGame()};h.appendChild(b)}document.getElementById('vp').textContent=draft.vow.progress;document.getElementById('vowTitle').textContent=draft.vow.title||'未設定'}
function openAssetPicker(replaceIndex=null){writeDraft();let u='assets.html?char='+encodeURIComponent(activeId);if(Number.isInteger(replaceIndex))u+='&replace='+replaceIndex;location.href=u}
function openAssetDetail(i){detailIndex=i;const a=draft.assets[i],abs=(a.abilities||[]).map(abilityParts),m=document.getElementById('managerModal');document.getElementById('managerTitle').textContent=a.name;document.getElementById('managerNote').textContent=a.summary||'説明なし';const h=document.getElementById('characterList');h.innerHTML=abs.map(x=>'<div class="char-row"><b>'+(x.active?'● ':'○ ')+x.label+'</b><div class="char-meta">'+(x.description||'説明なし')+'</div></div>').join('')+'<button id="changeAssetFromDetail" class="save-action github" style="width:100%;margin-top:6px">このアセットを選び直す</button>';document.getElementById('changeAssetFromDetail').onclick=()=>{m.classList.remove('open');openAssetPicker(i)};document.getElementById('saveStatus').textContent='';m.classList.add('open')}
function renderAssets(){const h=document.getElementById('assets');draft.assets=Array.isArray(draft.assets)?draft.assets:[];h.innerHTML='';document.getElementById('assetCount').textContent=draft.assets.length+'個';document.getElementById('assetAddTop').textContent=draft.assets.length<3?'＋初期 '+draft.assets.length+'/3':'＋追加 3XP';document.getElementById('assetAddTop').onclick=()=>openAssetPicker();const visible=draft.assets.length>3?draft.assets.slice(0,2):draft.assets.slice(0,3);visible.forEach((a,i)=>{const d=document.createElement('button');d.className='asset';d.innerHTML='<strong>'+a.name+'</strong><div>'+(a.abilities||[]).map(abilityParts).map(x=>'<span>'+x.label+'</span>').join(' / ')+'</div>';d.onclick=()=>openAssetDetail(i);h.appendChild(d)});if(draft.assets.length<3){for(let i=draft.assets.length;i<3;i++){const b=document.createElement('button');b.textContent='＋ アセットを追加';b.onclick=()=>openAssetPicker();h.appendChild(b)}}else if(draft.assets.length>3){const b=document.createElement('button');b.className='asset-more';b.textContent='ほか '+(draft.assets.length-2)+'個 / 一覧・追加';b.onclick=()=>openAssetPicker();h.appendChild(b)}}
function renderTattoos(){const h=document.getElementById('tattoos');h.innerHTML='';const e=Object.entries(draft.tattoos||{});document.getElementById('tattooHint').textContent=e.length?'タップで状態切替':'未設定';e.slice(0,8).forEach(([n,s])=>{const b=document.createElement('button');b.textContent=n+' '+(s==='cool'?'回復中':'使用可');b.onclick=()=>{draft.tattoos[n]=s==='cool'?'ready':'cool';writeDraft();renderGame()};h.appendChild(b)})}
function renderGame(){if(!draft)return;document.getElementById('charName').textContent=draft.name;['xp','health','spirit','supply','momentum'].forEach(k=>document.getElementById(k).textContent=draft.tracks[k]);['Edge','Heart','Iron','Shadow','Wits'].forEach(k=>document.getElementById('stat'+k).textContent=draft.stats[k.toLowerCase()]);renderMomentum();renderVow();renderAssets();renderTattoos()}
document.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>{const k=b.dataset.k,d=Number(b.dataset.d);if(k==='xp')draft.tracks.xp=clamp(draft.tracks.xp+d,0,99);if(['health','spirit','supply'].includes(k))draft.tracks[k]=clamp(draft.tracks[k]+d,0,5);if(k==='momentum')draft.tracks[k]=clamp(draft.tracks[k]+d,-6,10);writeDraft();renderGame()});
function openLoad(){const m=document.getElementById('managerModal');m.classList.add('open');document.getElementById('managerTitle').textContent='キャラクターをロード';document.getElementById('managerNote').textContent='最後に保存した状態を読み込みます。';const h=document.getElementById('characterList');h.innerHTML='';Object.values(saves).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')).forEach(c=>{const r=document.createElement('div');r.innerHTML='<b>'+c.name+'</b><button>ロード</button>';r.querySelector('button').onclick=()=>{startDraft(c.id,c);renderGame();m.classList.remove('open');show('gameScreen')};h.appendChild(r)})}
document.getElementById('homeLoad').onclick=()=>{discardDraft();openLoad()};document.getElementById('homeNew').onclick=()=>{discardDraft();document.getElementById('newName').value='';document.getElementById('newError').textContent='';show('newScreen')};document.getElementById('cancelNew').onclick=()=>show('homeScreen');
document.getElementById('createNew').onclick=()=>{const name=document.getElementById('newName').value.trim();const vals={edge:+document.getElementById('newEdge').value,heart:+document.getElementById('newHeart').value,iron:+document.getElementById('newIron').value,shadow:+document.getElementById('newShadow').value,wits:+document.getElementById('newWits').value};const arr=Object.values(vals).sort((a,b)=>b-a).join(',');if(!name){document.getElementById('newError').textContent='名前を入力してください。';return}if(arr!=='3,2,2,1,1'){document.getElementById('newError').textContent='能力値は 3 / 2 / 2 / 1 / 1 を1つずつ使います。';return}const id='char-'+Date.now();startDraft(id,{id,name,stats:vals,tracks:{health:5,spirit:5,supply:5,momentum:2,xp:0},vow:{title:'未設定',progress:0},assets:[],tattoos:{},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});renderGame();show('gameScreen')};
document.getElementById('goHome').onclick=()=>{discardDraft();history.replaceState(null,'',location.pathname);show('homeScreen')};document.getElementById('openSave').onclick=()=>{if(formalSave()){const b=document.getElementById('openSave'),old=b.textContent;b.textContent='保存済み';setTimeout(()=>b.textContent=old,700)}};document.getElementById('closeManager').onclick=()=>document.getElementById('managerModal').classList.remove('open');document.getElementById('managerModal').onclick=e=>{if(e.target===document.getElementById('managerModal'))document.getElementById('managerModal').classList.remove('open')};
document.getElementById('loadGithub').style.display='none';document.getElementById('exportSave').style.display='none';document.getElementById('importSave').style.display='none';document.getElementById('importFile').style.display='none';
const packed=readDraft();if(location.hash==='#game'){if(packed){activeId=packed.id;draft=migrate(packed.character)}else if(saves[activeId])startDraft(activeId,saves[activeId]);if(draft){renderGame();show('gameScreen')}else show('homeScreen')}else{discardDraft();show('homeScreen')}
