const STORE_KEY="ironsworn-characters-v1",ACTIVE_KEY="ironsworn-active-character",DRAFT_KEY="ironsworn-working-draft-v1",WHITE_ID="shirogane";
const whiteTemplate={id:WHITE_ID,name:"白金",stats:{edge:3,heart:1,iron:2,shadow:1,wits:2},tracks:{health:5,spirit:5,supply:3,momentum:3,xp:1},vow:{title:"アデルを連絡拠点まで守る",progress:0},assets:[{assetId:"last-of-people",name:"最後の民",type:"カスタム",abilities:[["荒野の子",true],["獣を捌く者",false],["異邦の眼",false]]},{assetId:"herbalist",name:"薬草師",type:"パス",abilities:[["薬草治療",true],["癒やし手",false],["滋養食",false]]},{assetId:"raven",name:"肉",type:"相棒",abilities:[["ずる賢い",false],["知る者",false],["勤勉",true]]}],tattoos:{"道標":"ready","鷹目":"ready","守骨":"ready","影歩":"ready","狩牙":"ready","止血":"cool","熾火":"ready","息潜":"ready"},createdAt:"2026-08-19T00:00:00+09:00",updatedAt:new Date().toISOString()};
const clone=x=>JSON.parse(JSON.stringify(x));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function migrate(c){if(!c)return c;c.assets=c.assets||[];const map={"最後の民":"last-of-people","薬草師":"herbalist","肉":"raven"};c.assets.forEach(a=>{if(!a.assetId&&map[a.name])a.assetId=map[a.name]});return c}
function loadStore(){let x={};try{x=JSON.parse(localStorage.getItem(STORE_KEY)||"{}")||{}}catch(e){}if(!x[WHITE_ID]){const w=clone(whiteTemplate);try{const old=JSON.parse(localStorage.getItem("shirogane-v3")||"null");if(old){w.tracks.xp=old.xp??w.tracks.xp;w.tracks.health=old.health??w.tracks.health;w.tracks.spirit=old.spirit??w.tracks.spirit;w.tracks.supply=old.supply??w.tracks.supply;w.tracks.momentum=old.momentum??w.tracks.momentum;w.vow.progress=old.vow??w.vow.progress;w.tattoos={...w.tattoos,...(old.tattoos||{})}}}catch(e){}x[WHITE_ID]=w}Object.values(x).forEach(migrate);localStorage.setItem(STORE_KEY,JSON.stringify(x));return x}
let store=loadStore(),activeId=localStorage.getItem(ACTIVE_KEY)||WHITE_ID,draft=null;
function readDraft(){try{const p=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||"null");if(p&&p.id&&p.character)return p}catch(e){}return null}
function writeDraft(){if(!draft)return;sessionStorage.setItem(DRAFT_KEY,JSON.stringify({id:activeId,character:draft}));localStorage.setItem(ACTIVE_KEY,activeId)}
function discardDraft(){draft=null;sessionStorage.removeItem(DRAFT_KEY)}
function startDraft(id,c){activeId=id;draft=migrate(clone(c));writeDraft();return draft}
function active(){if(draft)return draft;if(store[activeId])return startDraft(activeId,store[activeId]);return null}
function persistStore(){localStorage.setItem(STORE_KEY,JSON.stringify(store));localStorage.setItem(ACTIVE_KEY,activeId)}
function commitDraft(){if(!draft)return;draft.updatedAt=new Date().toISOString();store[activeId]=clone(draft);persistStore();writeDraft()}
function show(id){["homeScreen","newScreen","gameScreen"].forEach(x=>document.getElementById(x).classList.add("hidden"));document.getElementById(id).classList.remove("hidden")}
function renderMomentum(){const c=active(),h=document.getElementById("mtrack");h.innerHTML="";for(let v=-6;v<=10;v++){const b=document.createElement("button");b.className="mc"+(v===c.tracks.momentum?" on":"");b.textContent=v;b.onclick=()=>{c.tracks.momentum=v;writeDraft();renderGame()};h.appendChild(b)}}
function renderVow(){const c=active(),h=document.getElementById("vtrack");h.innerHTML="";for(let i=1;i<=10;i++){const b=document.createElement("button");b.className="vcell"+(i<=c.vow.progress?" on":"");b.onclick=()=>{c.vow.progress=c.vow.progress===i?i-1:i;writeDraft();renderGame()};h.appendChild(b)}document.getElementById("vp").textContent=c.vow.progress;document.getElementById("vowTitle").textContent=c.vow.title||"未設定"}
function openAssetPicker(replaceIndex=null){writeDraft();let u="assets.html?char="+encodeURIComponent(activeId);if(Number.isInteger(replaceIndex))u+="&replace="+replaceIndex;location.href=u}
function renderAssets(){const c=active(),h=document.getElementById("assets");c.assets=c.assets||[];h.innerHTML="";document.getElementById("assetCount").textContent=c.assets.length+"個";const top=document.getElementById("assetAddTop");top.textContent=c.assets.length<3?"＋初期 "+c.assets.length+"/3":"＋追加 3XP";top.onclick=()=>openAssetPicker();c.assets.slice(0,3).forEach((a,i)=>{const d=document.createElement("button");d.type="button";d.className="asset asset-edit";d.title="タップして選び直す";d.innerHTML='<div class="aname"><strong>'+a.name+'</strong><small>'+(a.type||"ASSET")+'　<span class="asset-edit-tag">変更</span></small></div><div class="abilities">'+(a.abilities||[]).map(x=>'<span class="ability '+(x[1]?"on":"")+'">'+x[0]+'</span>').join("")+"</div>";d.onclick=()=>openAssetPicker(i);h.appendChild(d)});if(c.assets.length<3){for(let i=c.assets.length;i<3;i++){const b=document.createElement("button");b.className="asset-add";b.innerHTML="＋ アセットを追加<br><small>初期枠 "+c.assets.length+" / 3</small>";b.onclick=()=>openAssetPicker();h.appendChild(b)}}else if(c.assets.length>3){const m=document.createElement("button");m.className="asset-more";m.innerHTML="ほか "+(c.assets.length-3)+"個<br>一覧・追加";m.onclick=()=>openAssetPicker();if(h.lastElementChild)h.replaceChild(m,h.lastElementChild);else h.appendChild(m)}}
function renderTattoos(){const c=active(),h=document.getElementById("tattoos"),e=Object.entries(c.tattoos||{});h.innerHTML="";document.getElementById("tattooHint").textContent=e.length?"タップで状態切替":"未設定";if(!e.length){h.innerHTML='<div class="empty-note">刺青なし</div>';return}e.slice(0,8).forEach(([n,s])=>{const b=document.createElement("button");b.className="tat"+(s==="cool"?" cool":"");b.innerHTML="<strong>"+n+"</strong><span>"+(s==="cool"?"回復中":"使用可")+"</span>";b.onclick=()=>{c.tattoos[n]=s==="cool"?"ready":"cool";writeDraft();renderGame()};h.appendChild(b)})}
function renderGame(){const c=active();if(!c)return;document.getElementById("charName").textContent=c.name;["xp","health","spirit","supply","momentum"].forEach(k=>document.getElementById(k).textContent=c.tracks[k]);["Edge","Heart","Iron","Shadow","Wits"].forEach(k=>document.getElementById("stat"+k).textContent=c.stats[k.toLowerCase()]);renderMomentum();renderVow();renderAssets();renderTattoos()}
document.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{const c=active(),k=b.dataset.k,d=Number(b.dataset.d);if(k==="xp")c.tracks.xp=clamp(c.tracks.xp+d,0,99);if(["health","spirit","supply"].includes(k))c.tracks[k]=clamp(c.tracks[k]+d,0,5);if(k==="momentum")c.tracks[k]=clamp(c.tracks[k]+d,-6,10);writeDraft();renderGame()});
function openManager(mode){const m=document.getElementById("managerModal");m.classList.add("open");document.getElementById("managerTitle").textContent=mode==="load"?"キャラクターをロード":"セーブ管理";document.getElementById("managerNote").textContent=mode==="load"?"最後に保存した状態を読み込みます。":"「ここに保存」を押した時だけ正式セーブされます。";document.getElementById("characterList").style.display=mode==="load"?"block":"none";document.getElementById("slotArea").style.display=mode==="save"?"block":"none";document.getElementById("loadGithub").style.display=mode==="load"?"block":"none";document.getElementById("saveStatus").textContent="";mode==="load"?renderCharacterList():renderSlots()}
function renderCharacterList(){const h=document.getElementById("characterList");h.innerHTML="";Object.values(store).sort((a,b)=>(b.updatedAt||"").localeCompare(a.updatedAt||"")).forEach(c=>{const r=document.createElement("div");r.className="char-row";const when=c.updatedAt?new Date(c.updatedAt).toLocaleString("ja-JP"):"";r.innerHTML='<div class="char-row-main"><div class="char-name">'+c.name+'</div><div class="char-meta">'+when+'</div></div><button>最後のセーブをロード</button>';r.querySelector("button").onclick=()=>{startDraft(c.id,c);renderGame();document.getElementById("managerModal").classList.remove("open");show("gameScreen")};h.appendChild(r)})}
const slotKey=n=>"ironsworn-slot-"+activeId+"-"+n;
function renderSlots(){const h=document.getElementById("slotArea");h.innerHTML="";for(let n=1;n<=3;n++){let x=null;try{x=JSON.parse(localStorage.getItem(slotKey(n))||"null")}catch(e){}const d=document.createElement("div");d.className="slot";const when=x?.savedAt?new Date(x.savedAt).toLocaleString("ja-JP"):"未保存";d.innerHTML='<div class="slot-top"><div class="slot-title">スロット '+n+'</div><div class="slot-meta">'+when+'</div></div><div class="slot-actions"><button data-save>ここに保存</button><button data-load '+(x?"":"disabled")+'>読み込む</button></div>';d.querySelector("[data-save]").onclick=()=>{commitDraft();localStorage.setItem(slotKey(n),JSON.stringify({savedAt:new Date().toISOString(),character:clone(active())}));renderSlots();document.getElementById("saveStatus").textContent="スロット "+n+" に正式保存しました。"};d.querySelector("[data-load]").onclick=()=>{let q=null;try{q=JSON.parse(localStorage.getItem(slotKey(n))||"null")}catch(e){}if(!q)return;draft=migrate(clone(q.character));draft.id=activeId;writeDraft();renderGame();document.getElementById("saveStatus").textContent="スロット "+n+" を一時的に読み込みました。保存するまでは正式データを上書きしません。"};h.appendChild(d)}}
async function loadGithubWhite(){const status=document.getElementById("saveStatus");status.textContent="GitHubの白金セーブを読み込み中…";try{const r=await fetch("saves/current.json?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw 0;const g=await r.json(),t=g.character?.tracks||{},v=(g.vows||[]).find(x=>x.id==="V004"),w=clone(store[WHITE_ID]||whiteTemplate);w.name=g.character?.name||"白金";w.stats={...w.stats,...(g.character?.stats||{})};w.tracks={health:t.health??w.tracks.health,spirit:t.spirit??w.tracks.spirit,supply:t.supply??w.tracks.supply,momentum:t.momentum??w.tracks.momentum,xp:t.xp??w.tracks.xp};w.vow={title:v?.title||w.vow.title,progress:v?.progress??w.vow.progress};w.tattoos={...w.tattoos,...(g.character?.tattoos||{})};w.updatedAt=new Date().toISOString();store[WHITE_ID]=migrate(w);activeId=WHITE_ID;persistStore();startDraft(WHITE_ID,w);renderGame();document.getElementById("managerModal").classList.remove("open");show("gameScreen")}catch(e){status.textContent="GitHubセーブを読み込めませんでした。"}}
document.getElementById("homeLoad").onclick=()=>{discardDraft();openManager("load")};
document.getElementById("homeNew").onclick=()=>{discardDraft();document.getElementById("newName").value="";document.getElementById("newError").textContent="";show("newScreen")};
document.getElementById("cancelNew").onclick=()=>{discardDraft();show("homeScreen")};
document.getElementById("createNew").onclick=()=>{const name=document.getElementById("newName").value.trim(),vals={edge:+document.getElementById("newEdge").value,heart:+document.getElementById("newHeart").value,iron:+document.getElementById("newIron").value,shadow:+document.getElementById("newShadow").value,wits:+document.getElementById("newWits").value},arr=Object.values(vals).sort((a,b)=>b-a).join(",");if(!name){document.getElementById("newError").textContent="名前を入力してください。";return}if(arr!=="3,2,2,1,1"){document.getElementById("newError").textContent="能力値は 3 / 2 / 2 / 1 / 1 を1つずつ使います。";return}const id="char-"+Date.now(),c={id,name,stats:vals,tracks:{health:5,spirit:5,supply:5,momentum:2,xp:0},vow:{title:"未設定",progress:0},assets:[],tattoos:{},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};startDraft(id,c);renderGame();show("gameScreen")};
document.getElementById("goHome").onclick=()=>{discardDraft();history.replaceState(null,"",location.pathname);show("homeScreen")};
document.getElementById("openSave").onclick=()=>openManager("save");
document.getElementById("closeManager").onclick=()=>document.getElementById("managerModal").classList.remove("open");
document.getElementById("managerModal").onclick=e=>{if(e.target===document.getElementById("managerModal"))document.getElementById("managerModal").classList.remove("open")};
document.getElementById("loadGithub").onclick=loadGithubWhite;
document.getElementById("exportSave").onclick=()=>{const blob=new Blob([JSON.stringify({format:"ironsworn-character-save-v1",savedAt:new Date().toISOString(),character:clone(active())},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(active()?.name||"ironsworn")+"-save.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
document.getElementById("importSave").onclick=()=>document.getElementById("importFile").click();
document.getElementById("importFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const j=JSON.parse(await f.text()),c=migrate(j.character||j);if(!c.name||!c.stats||!c.tracks)throw 0;const id=c.id&&c.id!==WHITE_ID?c.id:"char-"+Date.now();c.id=id;c.updatedAt=new Date().toISOString();store[id]=clone(c);activeId=id;persistStore();startDraft(id,c);renderGame();document.getElementById("managerModal").classList.remove("open");show("gameScreen")}catch(err){document.getElementById("saveStatus").textContent="このJSONは読み込めませんでした。"}e.target.value=""};
const packed=readDraft();if(location.hash==="#game"){if(packed){activeId=packed.id;draft=migrate(packed.character)}else if(store[activeId])startDraft(activeId,store[activeId]);if(active()){renderGame();show("gameScreen")}else show("homeScreen")}else{discardDraft();show("homeScreen")}
