(()=>{"use strict";
const STORE_KEY="ironsworn-characters-v1",ACTIVE_KEY="ironsworn-active-character";
const DATA_FILES=["assets/custom.json","assets/companions.json","assets/paths-1.json","assets/paths-2.json","assets/combat.json","assets/rituals.json"];
const $=id=>document.getElementById(id);
const el={backBtn:$("backBtn"),charLabel:$("charLabel"),costLabel:$("costLabel"),search:$("search"),filters:$("filters"),list:$("list"),modal:$("modal"),modalTitle:$("modalTitle"),modalText:$("modalText"),startAbilities:$("startAbilities"),cancelBtn:$("cancelBtn"),confirmBtn:$("confirmAssetBtn")};
let store={};try{store=JSON.parse(localStorage.getItem(STORE_KEY)||"{}")||{}}catch(e){store={}}
const params=new URLSearchParams(location.search),charId=params.get("char")||localStorage.getItem(ACTIVE_KEY),ch=charId?store[charId]:null;
if(!ch){location.replace("index.html");return}
ch.assets=Array.isArray(ch.assets)?ch.assets:[];ch.tracks=ch.tracks||{};if(!Number.isFinite(Number(ch.tracks.xp)))ch.tracks.xp=0;
let data=[],filter="すべて",query="",pending=null,pendingAbility=0;
const types=["すべて","相棒","パス","戦闘タレント","儀式","カスタム"];
const TERMS=[["Reach Your Destination","目的地に着いた時の判定"],["Undertake a Journey","旅を進める判定"],["Secure an Advantage","有利な状況を作る判定"],["Gather Information","情報を集める判定"],["Swear an Iron Vow","誓いを立てる判定"],["Fulfill Your Vow","誓いを達成できたか確かめる判定"],["Forge a Bond","相手との絆を結ぶ判定"],["Test Your Bond","相手との絆を試す判定"],["Face Desolation","絶望に耐える判定"],["Face Death","死に直面した時の判定"],["Endure Stress","精神的なダメージに耐える判定"],["Endure Harm","ケガやダメージに耐える判定"],["Enter the Fray","戦闘を始める時の判定"],["Turn the Tide","戦闘中に一度だけ流れを変える行動"],["Face Danger","危険に対処する判定"],["Check Your Gear","必要な装備があるか確かめる判定"],["Aid Your Ally","仲間を助ける判定"],["Make Camp","野営する時"],["Resupply","食料や物資を補給する判定"],["Sojourn","集落で休息・交流・補給する判定"],["Compel","説得・交渉・威圧する判定"],["Draw the Circle","一対一の決闘を始める判定"],["Strike","こちらが主導権を持って攻撃する判定"],["Clash","相手の攻撃に応戦する判定"],["Battle","集団戦の判定"],["Heal","治療する判定"],["Forsake Your Vow","誓いを捨てる"],["Maimed","重傷状態"],["Corrupted","汚染状態"],["Shadow","Shadow（隠密・ずる賢さ）"],["Heart","Heart（勇気・人との関わり）"],["Wits","Wits（知恵・観察力）"],["Iron","Iron（力・頑丈さ）"],["Edge","Edge（素早さ・遠距離）"]];
function easy(t){let s=String(t||"");TERMS.forEach(([a,b])=>s=s.split(a).join(b));return s}
function plainEffect(t){return easy(t).replace(/を強化。?$/,"で有利になる。").replace(/を補助。?$/,"を使う判定で有利になる。").replace(/に強い。?$/,"で有利になる。")}
const count=()=>ch.assets.length,cost=()=>count()<3?0:3;
function save(){ch.updatedAt=new Date().toISOString();store[charId]=ch;localStorage.setItem(STORE_KEY,JSON.stringify(store));localStorage.setItem(ACTIVE_KEY,charId)}
function status(){el.charLabel.textContent=`${ch.name}　アセット ${count()}個`;el.costLabel.textContent=cost()===0?`初期枠 ${count()} / 3`:`追加：3 XP（所持 ${Number(ch.tracks.xp)||0} XP）`}
function owned(a){return ch.assets.some(x=>x.assetId===a.id||x.id===a.id||x.name===a.name)}
function renderFilters(){el.filters.innerHTML="";types.forEach(t=>{const b=document.createElement("button");b.type="button";b.className="filter"+(t===filter?" on":"");b.textContent=t;b.addEventListener("click",()=>{filter=t;renderFilters();renderList()});el.filters.appendChild(b)})}
function renderList(){el.list.innerHTML="";const q=query.trim().toLowerCase(),arr=data.filter(a=>(filter==="すべて"||a.type===filter)&&(!q||[a.name,a.type,a.summary,...(a.abilities||[]).flatMap(x=>[x.label,x.description])].join(" ").toLowerCase().includes(q)));if(!arr.length){el.list.innerHTML='<div class="empty">該当するアセットがありません。</div>';return}arr.forEach(a=>{const own=owned(a),c=document.createElement("div");c.className="card"+(own?" owned":"");c.innerHTML=`<div class="card-top"><div class="name">${a.name}</div><div class="type">${a.type}</div></div><div class="summary"><b>ざっくり：</b>${easy(a.summary)}</div>${a.requirement?`<div class="req"><b>取得条件：</b>${easy(a.requirement)}</div>`:""}<div class="what-title">このアセットでできること</div><div class="abilities">${(a.abilities||[]).map((x,i)=>`<div class="ability"><div class="ability-name"><span class="num">${i+1}</span><b>${x.label}</b>${i===0&&!a.chooseStartingAbility?'<span class="start-tag">最初から</span>':''}</div><div class="effect"><span class="effect-label">使うと</span><span>${plainEffect(x.description)}</span></div></div>`).join("")}</div><button type="button" class="choose" ${own?"disabled":""}>${own?"取得済み":(cost()?"3 XPで取得":"選ぶ")}</button>`;const chooseBtn=c.querySelector(".choose");if(!own)chooseBtn.addEventListener("click",()=>begin(a));el.list.appendChild(c)})}
function begin(a){if(owned(a))return;if(cost()>0&&(Number(ch.tracks.xp)||0)<3){alert("このアセットを追加するにはXPが3必要です。");return}pending=a;pendingAbility=0;el.modalTitle.textContent=a.name;el.modalText.textContent=a.chooseStartingAbility?"最初から使える能力を1つ選んでください。":"このアセットを追加します。1番目の能力が最初から使えます。";el.startAbilities.innerHTML="";if(a.chooseStartingAbility)(a.abilities||[]).forEach((x,i)=>{const b=document.createElement("button");b.type="button";b.className="start-ability"+(i===0?" selected":"");b.innerHTML=`<strong>${x.label}</strong><span>${plainEffect(x.description)}</span>`;b.addEventListener("click",()=>{pendingAbility=i;el.startAbilities.querySelectorAll(".start-ability").forEach((z,j)=>z.classList.toggle("selected",j===i))});el.startAbilities.appendChild(b)});el.modal.classList.add("open");el.modal.setAttribute("aria-hidden","false")}
function closeModal(){pending=null;el.modal.classList.remove("open");el.modal.setAttribute("aria-hidden","true")}
function confirmAssetSelection(){if(!pending)return;const xpCost=cost(),currentXp=Number(ch.tracks.xp)||0;if(xpCost>0){if(currentXp<xpCost){alert("XPが足りません。");return}ch.tracks.xp=currentXp-xpCost}ch.assets.push({assetId:pending.id,name:pending.name,type:pending.type,abilities:(pending.abilities||[]).map((x,i)=>[x.label,i===pendingAbility]),source:"asset-library"});save();closeModal();location.href="index.html#game"}
el.backBtn.addEventListener("click",()=>location.href="index.html#game");el.search.addEventListener("input",e=>{query=e.target.value;renderList()});el.cancelBtn.addEventListener("click",closeModal);el.confirmBtn.addEventListener("click",confirmAssetSelection);el.modal.addEventListener("click",e=>{if(e.target===el.modal)closeModal()});
Promise.all(DATA_FILES.map(f=>fetch(`${f}?v=asset3`,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(f);return r.json()}))).then(parts=>{data=parts.flat();status();renderFilters();renderList()}).catch(err=>{console.error(err);el.list.innerHTML='<div class="empty">アセットデータを読み込めませんでした。</div>'});
})();