(()=>{'use strict';
const DRAFT_KEY='ironsworn-private-new-draft-v1';
const TOKEN_KEY='ironsworn-private-save-token-v1';
const OWNER='namiyukuta-cmd',REPO='private-game-data',BRANCH='main',ROOT='ironsworn-solo';
const API='https://api.github.com/repos/'+OWNER+'/'+REPO;
const $=id=>document.getElementById(id),card=$('newCard'),error=$('newError'),next=$('nextBtn'),prev=$('prevBtn');
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function blank(){const now=new Date().toISOString();return{version:1,id:'char-'+Date.now(),step:0,createdAt:now,updatedAt:now,data:{name:'',concept:'',stats:{edge:3,heart:1,iron:2,shadow:1,wits:2},assets:['','',''],worldName:'',worldTruths:'',startLocation:'',bonds:['','',''],equipment:'',backgroundVow:'',backgroundVowRank:'Extreme',incitingIncident:'',startMode:'normal',openingScene:'',initialVow:'',initialVowRank:'Dangerous'}}}
function load(){try{return JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'null')||blank()}catch(e){return blank()}}
let state=load();
function saveDraft(){state.updatedAt=new Date().toISOString();sessionStorage.setItem(DRAFT_KEY,JSON.stringify(state))}
function field(id,label,value,placeholder='',area=false){return '<label class="field"><span>'+label+'</span>'+(area?'<textarea id="'+id+'" placeholder="'+esc(placeholder)+'">'+esc(value)+'</textarea>':'<input id="'+id+'" value="'+esc(value)+'" placeholder="'+esc(placeholder)+'">')+'</label>'}
function rank(name,value,opts){return '<div class="rank-row">'+opts.map(x=>'<label class="choice"><input type="radio" name="'+name+'" value="'+x+'" '+(value===x?'checked':'')+'><span>'+x+'</span></label>').join('')+'</div>'}
function render(){const d=state.data,n=state.step;$('stepLabel').textContent=(n+1)+' / 8';$('progressBar').style.width=((n+1)/8*100)+'%';prev.style.visibility=n===0?'hidden':'visible';next.textContent=n===7?'Private Gameへ保存':'次へ';error.textContent='';
if(n===0){card.innerHTML='<div class="kicker">CHARACTER</div><h1>キャラクター</h1><p class="help">このNEW画面だけで新しいソロ用データを作ります。既存Ironswornのセーブには触れません。</p>'+field('name','名前',d.name,'キャラクター名')+field('concept','人物像・性格・背景',d.concept,'例：旅の占い師。口数は少ない。',true)+'<label class="field"><span>能力値 <small>3 / 2 / 2 / 1 / 1 を1つずつ</small></span><div class="stats">'+['edge','heart','iron','shadow','wits'].map(k=>'<label class="stat"><span>'+k.toUpperCase()+'</span><select id="stat-'+k+'">'+[1,2,3].map(v=>'<option '+(d.stats[k]===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label>').join('')+'</div></label><p class="help">開始値：Health 5 / Spirit 5 / Supply 5 / Momentum 2 / XP 0</p>'}
if(n===1){card.innerHTML='<div class="kicker">ASSETS</div><h1>初期アセット</h1><p class="help">既存のアセット選択画面には接続しません。このNEWデータ内だけに3つ記録します。</p><div class="asset-grid">'+d.assets.map((v,i)=>field('asset'+i,'アセット '+(i+1),v,'アセット名')).join('')+'</div>'}
if(n===2){card.innerHTML='<div class="kicker">WORLD</div><h1>世界</h1><p class="help">新しいゲーム専用の世界情報です。</p>'+field('worldName','世界名',d.worldName,'例：ヒマリの世界')+field('worldTruths','世界の基本設定',d.worldTruths,'時代、地域、雰囲気、魔法の有無など。',true)+field('startLocation','物語の開始地点',d.startLocation,'例：北部の小さな町')}
if(n===3){card.innerHTML='<div class="kicker">BACKGROUND</div><h1>背景</h1><p class="help">背景の絆、装備、長く抱えている誓いを記録します。</p><div class="bond-grid">'+d.bonds.map((v,i)=>field('bond'+i,'絆 '+(i+1),v,'空欄でもOK')).join('')+'</div>'+field('equipment','重要な装備・持ち物',d.equipment,'物語上意味のある物',true)+field('backgroundVow','背景の誓い',d.backgroundVow,'長く抱えている大きな誓い')+'<label class="field"><span>背景の誓いのランク</span>'+rank('backgroundRank',d.backgroundVowRank,['Extreme','Epic'])+'</label>'}
if(n===4){card.innerHTML='<div class="kicker">INCITING INCIDENT</div><h1>発端事件</h1><p class="help">キャラクターが動かざるを得なくなった問題です。</p>'+field('incident','何が起きた？',d.incitingIncident,'事件、依頼、危機、発見など。',true)}
if(n===5){card.innerHTML='<div class="kicker">OPENING</div><h1>開始場面</h1><label class="field"><span>開始方法</span><div class="scene-row"><label class="choice"><input type="radio" name="startMode" value="normal" '+(d.startMode==='normal'?'checked':'')+'><span>日常から始める</span></label><label class="choice"><input type="radio" name="startMode" value="in-media-res" '+(d.startMode==='in-media-res'?'checked':'')+'><span>事件の最中から</span></label></div></label>'+field('openingScene','最初の場面',d.openingScene,'どこで、誰がいて、何が起きている？',true)}
if(n===6){card.innerHTML='<div class="kicker">IRON VOW</div><h1>最初の誓い</h1>'+field('initialVow','この事件に対して何を誓う？',d.initialVow,'例：消えた旅人を見つける')+'<label class="field"><span>ランク</span>'+rank('initialRank',d.initialVowRank,['Troublesome','Dangerous','Formidable'])+'</label>'}
if(n===7){const token=localStorage.getItem(TOKEN_KEY)||'';card.innerHTML='<div class="kicker">PRIVATE SAVE</div><h1>Private Gameへ保存</h1><p class="help">保存先は <code>private-game-data / ironsworn-solo</code> です。既存Ironswornのローカルセーブや既存ゲーム用領域は使いません。</p><div class="summary"><div><b>キャラクター</b><span>'+esc(d.name)+' / '+esc(d.assets.join('、'))+'</span></div><div><b>世界</b><span>'+esc(d.worldName)+'\n'+esc(d.startLocation)+'</span></div><div><b>最初の誓い</b><span>'+esc(d.initialVow)+' / '+esc(d.initialVowRank)+'</span></div></div><div class="token-box">'+field('privateToken','GitHubトークン',token?'保存済み（変更する場合だけ入力）':'','private-game-dataへ書き込めるトークン')+'<p class="help">入力した場合はこの端末に保存します。このNEW画面だけが使用します。</p></div>'}}
function capture(){const d=state.data,n=state.step;if(n===0){d.name=$('name').value.trim();d.concept=$('concept').value.trim();['edge','heart','iron','shadow','wits'].forEach(k=>d.stats[k]=Number($('stat-'+k).value))}if(n===1)d.assets=[0,1,2].map(i=>$('asset'+i).value.trim());if(n===2){d.worldName=$('worldName').value.trim();d.worldTruths=$('worldTruths').value.trim();d.startLocation=$('startLocation').value.trim()}if(n===3){d.bonds=[0,1,2].map(i=>$('bond'+i).value.trim());d.equipment=$('equipment').value.trim();d.backgroundVow=$('backgroundVow').value.trim();d.backgroundVowRank=document.querySelector('input[name="backgroundRank"]:checked').value}if(n===4)d.incitingIncident=$('incident').value.trim();if(n===5){d.startMode=document.querySelector('input[name="startMode"]:checked').value;d.openingScene=$('openingScene').value.trim()}if(n===6){d.initialVow=$('initialVow').value.trim();d.initialVowRank=document.querySelector('input[name="initialRank"]:checked').value}if(n===7){const t=$('privateToken').value.trim();if(t&&!t.includes('保存済み'))localStorage.setItem(TOKEN_KEY,t)}saveDraft()}
function validate(){const d=state.data,n=state.step;if(n===0){if(!d.name)return'名前を入力してください。';if(Object.values(d.stats).sort((a,b)=>b-a).join(',')!=='3,2,2,1,1')return'能力値は 3 / 2 / 2 / 1 / 1 を1つずつ使います。'}if(n===1&&d.assets.filter(Boolean).length!==3)return'アセットを3つ入力してください。';if(n===2&&(!d.worldName||!d.startLocation))return'世界名と開始地点を入力してください。';if(n===3&&!d.backgroundVow)return'背景の誓いを入力してください。';if(n===4&&!d.incitingIncident)return'発端事件を入力してください。';if(n===5&&!d.openingScene)return'最初の場面を入力してください。';if(n===6&&!d.initialVow)return'最初の誓いを入力してください。';if(n===7&&!localStorage.getItem(TOKEN_KEY)&&!$('privateToken').value.trim())return'Private Gameへ保存するGitHubトークンを入力してください。';return''}
function safeId(s){return String(s||'character').replace(/[^A-Za-z0-9._-]/g,'-')||'character'}
function utf8b64(text){const bytes=new TextEncoder().encode(text);let out='';for(let i=0;i<bytes.length;i+=32768)out+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(out)}
async function request(path,opt={}){const token=localStorage.getItem(TOKEN_KEY)||'';const headers={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(opt.headers||{})};if(token)headers.Authorization='Bearer '+token;const r=await fetch(API+path,{...opt,headers});let body=null;try{body=await r.json()}catch(e){}if(!r.ok){const e=new Error((body&&body.message)||('GitHub API '+r.status));e.status=r.status;throw e}return body}
async function getFile(path){const p=path.split('/').map(encodeURIComponent).join('/');try{return await request('/contents/'+p+'?ref='+encodeURIComponent(BRANCH))}catch(e){if(e.status===404)return null;throw e}}
async function readJson(path,fallback){const f=await getFile(path);if(!f)return fallback;const raw=(f.content||'').replace(/\n/g,'');const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));try{return JSON.parse(new TextDecoder().decode(bytes))}catch(e){return fallback}}
async function putJson(path,obj,message){const old=await getFile(path);const p=path.split('/').map(encodeURIComponent).join('/');const payload={message,content:utf8b64(JSON.stringify(obj,null,2)),branch:BRANCH};if(old?.sha)payload.sha=old.sha;return request('/contents/'+p,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}
function buildCharacter(){const d=state.data,now=new Date().toISOString();return{id:state.id,name:d.name,profile:d.concept,stats:clone(d.stats),tracks:{health:5,spirit:5,supply:5,momentum:2,momentumMax:10,momentumReset:2,xp:0},vow:{title:d.initialVow,progress:0,rank:d.initialVowRank,status:'active'},backgroundVow:{title:d.backgroundVow,progress:0,rank:d.backgroundVowRank,status:'active'},bonds:d.bonds.filter(Boolean).map(name=>({name,ticks:1,background:true})),assets:d.assets.map((name,i)=>({id:'private-asset-'+(i+1),name,type:'ASSET'})),equipment:d.equipment,notes:d.concept,tattoos:{},setup:{complete:true,source:'new.html',world:{name:d.worldName,truths:d.worldTruths,startLocation:d.startLocation},incitingIncident:d.incitingIncident,startMode:d.startMode,openingScene:d.openingScene,completedAt:now},createdAt:state.createdAt,updatedAt:now}}
async function savePrivate(){const d=state.data,character=buildCharacter(),savedAt=new Date().toISOString(),id=safeId(state.id),path=ROOT+'/'+id+'/save_0001.json';next.disabled=true;prev.disabled=true;next.textContent='保存中…';error.textContent='';try{await putJson(path,{format:'ironsworn-private-save-v1',id:state.id,name:d.name,path,savedAt,character},'Save Ironsworn private game: '+d.name);const indexPath=ROOT+'/index.json';const index=await readJson(indexPath,{format:'ironsworn-private-save-index-v1',saves:[]});index.format=index.format||'ironsworn-private-save-index-v1';index.saves=Array.isArray(index.saves)?index.saves:[];const item={id:state.id,name:d.name,path,updatedAt:savedAt};const at=index.saves.findIndex(x=>x.id===state.id);if(at>=0)index.saves[at]=item;else index.saves.unshift(item);index.updatedAt=savedAt;await putJson(indexPath,index,'Update Ironsworn private save index');sessionStorage.removeItem(DRAFT_KEY);card.innerHTML='<div class="saved"><strong>Private Gameへ保存しました。</strong><span>'+esc(path)+'</span></div>';$('stepLabel').textContent='保存完了';$('progressBar').style.width='100%';prev.style.display='none';next.style.display='none'}catch(e){error.textContent='保存失敗：'+e.message;next.disabled=false;prev.disabled=false;next.textContent='Private Gameへ保存'}}
prev.onclick=()=>{capture();if(state.step>0){state.step--;saveDraft();render()}};
next.onclick=async()=>{capture();const msg=validate();if(msg){error.textContent=msg;return}if(state.step<7){state.step++;saveDraft();render()}else await savePrivate()};
render();
})();
