(()=>{'use strict';
const DRAFT_KEY='ironsworn-private-new-draft-v1';
const CUSTOM_KEY='ironsworn-private-custom-assets-v1';
const DATA_FILES=['assets/custom.json','assets/companions.json','assets/paths-1.json','assets/paths-2.json','assets/combat.json','assets/rituals.json'];
const $=id=>document.getElementById(id);
const el={backBtn:$('backBtn'),charLabel:$('charLabel'),costLabel:$('costLabel'),search:$('search'),filters:$('filters'),list:$('list'),modal:$('modal'),modalTitle:$('modalTitle'),modalText:$('modalText'),startAbilities:$('startAbilities'),cancelBtn:$('cancelBtn'),confirmBtn:$('confirmAssetBtn'),customNewBtn:$('customNewBtn'),customModal:$('customModal'),customName:$('customName'),customType:$('customType'),customSummary:$('customSummary'),customA1:$('customA1'),customD1:$('customD1'),customA2:$('customA2'),customD2:$('customD2'),customA3:$('customA3'),customD3:$('customD3'),customError:$('customError'),customCancelBtn:$('customCancelBtn'),customCreateBtn:$('customCreateBtn')};
let state=null;try{state=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'null')}catch(e){}
if(!state||!state.data){location.replace('new.html');return}
const d=state.data;
function normalizeAsset(x,i){if(!x)return null;if(typeof x==='string')return x.trim()?{assetId:'legacy-'+i,name:x.trim(),type:'ASSET',summary:'',abilities:[],source:'new-private'}:null;return x&&x.name?x:null}
d.assets=(Array.isArray(d.assets)?d.assets:[]).map(normalizeAsset).filter(Boolean);
function saveState(){state.updatedAt=new Date().toISOString();sessionStorage.setItem(DRAFT_KEY,JSON.stringify(state))}
saveState();
let data=[],filter='すべて',query='',pending=null,pendingAbility=0;
const types=['すべて','相棒','パス','戦闘タレント','儀式','カスタム'];
const TERMS=[['Reach Your Destination','目的地に着いた時の判定'],['Undertake a Journey','旅を進める判定'],['Secure an Advantage','有利な状況を作る判定'],['Gather Information','情報を集める判定'],['Swear an Iron Vow','誓いを立てる判定'],['Fulfill Your Vow','誓いを達成できたか確かめる判定'],['Forge a Bond','相手との絆を結ぶ判定'],['Test Your Bond','相手との絆を試す判定'],['Face Desolation','絶望に耐える判定'],['Face Death','死に直面した時の判定'],['Endure Stress','精神的なダメージに耐える判定'],['Endure Harm','ケガやダメージに耐える判定'],['Enter the Fray','戦闘を始める時の判定'],['Turn the Tide','戦闘中に一度だけ流れを変える行動'],['Face Danger','危険に対処する判定'],['Check Your Gear','必要な装備があるか確かめる判定'],['Aid Your Ally','仲間を助ける判定'],['Make Camp','野営する時'],['Resupply','食料や物資を補給する判定'],['Sojourn','集落で休息・交流・補給する判定'],['Compel','説得・交渉・威圧する判定'],['Draw the Circle','一対一の決闘を始める判定'],['Strike','こちらが主導権を持って攻撃する判定'],['Clash','相手の攻撃に応戦する判定'],['Battle','集団戦の判定'],['Heal','治療する判定'],['Forsake Your Vow','誓いを捨てる'],['Maimed','重傷状態'],['Corrupted','汚染状態'],['Shadow','Shadow（隠密・ずる賢さ）'],['Heart','Heart（勇気・人との関わり）'],['Wits','Wits（知恵・観察力）'],['Iron','Iron（力・頑丈さ）'],['Edge','Edge（素早さ・遠距離）']];
function easy(t){let s=String(t||'');TERMS.forEach(([a,b])=>s=s.split(a).join(b));return s}
function plainEffect(t){return easy(t).replace(/を強化。?$/,'で有利になる。').replace(/を補助。?$/,'を使う判定で有利になる。').replace(/に強い。?$/,'で有利になる。')}
function sameAsset(x,a){return !!x&&(x.assetId===a.id||x.assetId===a.assetId||x.name===a.name)}
function owned(a){return d.assets.some(x=>sameAsset(x,a))}
function status(){el.charLabel.textContent=(d.name||'新しいキャラクター')+'　初期アセット '+d.assets.length+' / 3';el.costLabel.textContent='初期3枠：XP消費なし'}
function renderFilters(){el.filters.innerHTML='';types.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='filter'+(t===filter?' on':'');b.textContent=t;b.onclick=()=>{filter=t;renderFilters();renderList()};el.filters.appendChild(b)})}
function renderList(){el.list.innerHTML='';const q=query.trim().toLowerCase();const arr=data.filter(a=>(filter==='すべて'||a.type===filter)&&(!q||[a.name,a.type,a.summary,...(a.abilities||[]).flatMap(x=>[x.label,x.description])].join(' ').toLowerCase().includes(q)));if(!arr.length){el.list.innerHTML='<div class="empty">該当するアセットがありません。</div>';return}arr.forEach(a=>{const own=owned(a),full=d.assets.length>=3,c=document.createElement('div');c.className='card'+(own?' owned':'');c.innerHTML='<div class="card-top"><div class="name">'+a.name+(a.userCustom?' <span class="user-custom-tag">自作</span>':'')+'</div><div class="type">'+a.type+'</div></div><div class="summary"><b>ざっくり：</b>'+easy(a.summary)+'</div>'+(a.requirement?'<div class="req"><b>取得条件：</b>'+easy(a.requirement)+'</div>':'')+'<div class="what-title">このアセットでできること</div><div class="abilities">'+(a.abilities||[]).map((x,i)=>'<div class="ability"><div class="ability-name"><span class="num">'+(i+1)+'</span><b>'+x.label+'</b>'+(i===0&&!a.chooseStartingAbility?'<span class="start-tag">最初から</span>':'')+'</div><div class="effect"><span class="effect-label">使うと</span><span>'+plainEffect(x.description)+'</span></div></div>').join('')+'</div><button type="button" class="choose" '+(own||full?'disabled':'')+'>'+(own?'選択済み':full?'3つ選択済み':'選ぶ')+'</button>';const b=c.querySelector('.choose');if(!own&&!full)b.onclick=()=>begin(a);el.list.appendChild(c)})}
function begin(a){pending=a;pendingAbility=0;el.modalTitle.textContent=a.name;el.modalText.textContent=a.chooseStartingAbility?'最初から使える能力を1つ選んでください。':'このアセットを初期アセットに追加します。1番目の能力が最初から使えます。';el.startAbilities.innerHTML='';if(a.chooseStartingAbility)(a.abilities||[]).forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.className='start-ability'+(i===0?' selected':'');b.innerHTML='<strong>'+x.label+'</strong><span>'+plainEffect(x.description)+'</span>';b.onclick=()=>{pendingAbility=i;el.startAbilities.querySelectorAll('.start-ability').forEach((z,j)=>z.classList.toggle('selected',j===i))};el.startAbilities.appendChild(b)});el.modal.classList.add('open');el.modal.setAttribute('aria-hidden','false')}
function closeModal(){pending=null;el.modal.classList.remove('open');el.modal.setAttribute('aria-hidden','true')}
function confirmSelection(){if(!pending||d.assets.length>=3)return;const obj={assetId:pending.id,name:pending.name,type:pending.type,summary:pending.summary||'',abilities:(pending.abilities||[]).map((x,i)=>[x.label,i===pendingAbility,x.description||'']),source:pending.userCustom?'private-custom':'asset-library',userCustom:!!pending.userCustom};d.assets.push(obj);saveState();closeModal();location.href='new.html'}
function loadCustoms(){try{return JSON.parse(localStorage.getItem(CUSTOM_KEY)||'[]')||[]}catch(e){return[]}}
function openCustom(){[el.customName,el.customSummary,el.customA1,el.customD1,el.customA2,el.customD2,el.customA3,el.customD3].forEach(x=>x.value='');el.customType.value='カスタム';el.customError.textContent='';el.customModal.classList.add('open');el.customModal.setAttribute('aria-hidden','false')}
function closeCustom(){el.customModal.classList.remove('open');el.customModal.setAttribute('aria-hidden','true')}
function createCustom(){const name=el.customName.value.trim(),a1=el.customA1.value.trim();if(!name){el.customError.textContent='アセット名を入力してください。';return}if(!a1){el.customError.textContent='能力1の名前を入力してください。';return}const abilities=[];[[el.customA1,el.customD1],[el.customA2,el.customD2],[el.customA3,el.customD3]].forEach(([n,x])=>{const label=n.value.trim();if(label)abilities.push({label,description:x.value.trim()||'効果を自由に決める。'})});const a={id:'private-custom-'+Date.now(),name,type:el.customType.value,summary:el.customSummary.value.trim()||'自作のカスタムアセット。',abilities,chooseStartingAbility:abilities.length>1,requirement:null,userCustom:true};const cs=loadCustoms();cs.push(a);localStorage.setItem(CUSTOM_KEY,JSON.stringify(cs));data.push(a);closeCustom();renderList();begin(a)}
el.backBtn.onclick=()=>location.href='new.html';el.search.oninput=e=>{query=e.target.value;renderList()};el.cancelBtn.onclick=closeModal;el.confirmBtn.onclick=confirmSelection;el.modal.onclick=e=>{if(e.target===el.modal)closeModal()};el.customNewBtn.onclick=openCustom;el.customCancelBtn.onclick=closeCustom;el.customCreateBtn.onclick=createCustom;el.customModal.onclick=e=>{if(e.target===el.customModal)closeCustom()};
Promise.all(DATA_FILES.map(f=>fetch(f+'?v=asset7',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(f);return r.json()}))).then(parts=>{data=parts.flat().concat(loadCustoms());status();renderFilters();renderList()}).catch(err=>{console.error(err);el.list.innerHTML='<div class="empty">アセットデータを読み込めませんでした。</div>'});
})();