(()=>{'use strict';
const OWNER='namiyukuta-cmd',REPO='private-game-data',BRANCH='main',ROOT='ironsworn-solo',TOKEN_KEY='ironsworn-private-save-token-v1';
const api='https://api.github.com/repos/'+OWNER+'/'+REPO;const clean=s=>String(s||'character').replace(/[^A-Za-z0-9._-]/g,'-');
const token=()=>localStorage.getItem(TOKEN_KEY)||'';const b64=s=>{const bytes=new TextEncoder().encode(s);let out='';for(let i=0;i<bytes.length;i+=32768)out+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(out)};
async function request(path,opt={}){const t=token();if(!t)throw new Error('PRIVATE_TOKEN_REQUIRED');const r=await fetch(api+path,{...opt,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+t,...opt.headers}});let j={};try{j=await r.json()}catch(e){}if(!r.ok){const e=new Error(j.message||('GitHub '+r.status));e.status=r.status;throw e}return j}
async function read(path){try{const f=await request('/contents/'+path.split('/').map(encodeURIComponent).join('/')+'?ref='+BRANCH);const raw=(f.content||'').replace(/\n/g,'');const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));return {data:JSON.parse(new TextDecoder().decode(bytes)),sha:f.sha}}catch(e){if(e.status===404)return {data:null,sha:null};throw e}}
async function write(path,data,message){const old=await read(path),body={message,branch:BRANCH,content:b64(JSON.stringify(data,null,2)+'\n')};if(old.sha)body.sha=old.sha;return request('/contents/'+path.split('/').map(encodeURIComponent).join('/'),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
function documentFromDraft(){return {format:'ironsworn-solo-save-v1',schemaVersion:1,id:draft.id,name:draft.name,updatedAt:new Date().toISOString(),character:JSON.parse(JSON.stringify(draft))}}
async function save(){if(!token()){const t=prompt('非公開の private-game-data に保存するGitHubトークンを入力してください。\n対象リポジトリの Contents: Read and write が必要です。');if(!t)return false;localStorage.setItem(TOKEN_KEY,t.trim())}const doc=documentFromDraft(),id=clean(doc.id),idxPath=ROOT+'/index.json',old=await read(idxPath),idx=old.data||{format:'ironsworn-solo-index-v1',saves:[]};const n=idx.saves.filter(x=>x.characterId===doc.id).length+1,path=ROOT+'/'+id+'/save_'+String(n).padStart(4,'0')+'.json';await write(path,doc,'Save Ironsworn solo: '+doc.name);idx.saves.push({characterId:doc.id,name:doc.name,path,updatedAt:doc.updatedAt});idx.updatedAt=doc.updatedAt;await write(idxPath,idx,'Update Ironsworn solo save index');return true}
async function list(){const x=await read(ROOT+'/index.json');return (x.data?.saves||[]).slice().sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''))}
async function load(path){const x=await read(path);const c=x.data?.character;if(!c)throw new Error('セーブデータが壊れています。');const saves=JSON.parse(localStorage.getItem('ironsworn-saves-v3')||'{}');saves[c.id]=c;localStorage.setItem('ironsworn-saves-v3',JSON.stringify(saves));localStorage.setItem('ironsworn-active-character',c.id);sessionStorage.setItem('ironsworn-working-draft-v3',JSON.stringify({id:c.id,character:c}));location.href='main.html'}
window.IronswornPrivateSave={tokenKey:TOKEN_KEY,setToken:t=>localStorage.setItem(TOKEN_KEY,t.trim()),clearToken:()=>localStorage.removeItem(TOKEN_KEY),hasToken:()=>!!token(),save,list,load};
const btn=document.getElementById('openSave');if(btn)btn.onclick=async()=>{if(typeof formalSave==='function')formalSave();btn.disabled=true;btn.textContent='保存中…';try{await save();btn.textContent='保存済み'}catch(e){btn.textContent='失敗';alert(e.message==='PRIVATE_TOKEN_REQUIRED'?'GitHubトークンが必要です。':e.message)}finally{setTimeout(()=>{btn.disabled=false;btn.textContent='セーブ'},1100)}};
})();
